[package]
name = "candle-diffusion"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
candle = { package = "candle-core", version = "0.11.0" }
candle-nn = "0.11.0"
candle-transformers = "0.11.0"
clap = { version = "4.2.4", features = ["derive"] }
hf-hub = "0.5.0"
image = { version = "0.25.2", default-features = false, features = ["png", "jpeg"] }
serde_json = "1.0.99"
tokenizers = { version = "0.22.0", default-features = false, features = ["onig"] }

[features]
default = ["metal"]
metal = ["candle/metal", "candle-nn/metal", "candle-transformers/metal"]

[profile.release]
debug = false
